
# type ContributionsAggregation {
#   sum: Int
#   contributorCount: Int
#   contributionCount: Int
# }

# type ContributionsByCode {
#   ind: ContributionsAggregation
#   com: ContributionsAggregation
#   oth: ContributionsAggregation
#   pty: ContributionsAggregation
#   scc: ContributionsAggregation
# }

type ContributionsSumByCode {
  ind: Int
  com: Int
  oth: Int
  pty: Int
  scc: Int
}

type ContributionsSumByMethod {
  inKind: Int @deprecated
  individual: Int @deprecated
  other: Int @deprecated
  monetary: ContributionsSumByCode
  nonMonetary: ContributionsSumByCode
  # loans: ContributionsSumByCode
  # monetaryAggregation: ContributionsByCode
}
